### ISSUE TITLE
中国空中公园通联 0-9 区奖状申请规则及办法

### ISSUE THREAD

**Issue by thefish12357** [HamCQ/Handbook#1]
# 活动介绍
与IOTA理念相似，空中公园（Parks on the Air--POTA）是为了鼓励与位于世界各地的公园中的无线电台取得联系，此前，中国大陆及港澳地区没有公园加入到此项目中，现在经过相关协调，目前pota活动已进入中国地区(包含港澳台)，相关公园信息逐步完善。

# 第 一 条：目的
为鼓励业余无线电爱好者走出家门到各地公园与国内外业余无线电台中通联，由 POTA-BY 地区管理员 [BH3XZT](https://forum.hamcq.cn/u/18) 提议，中国空中公园奖状管理组联合发起设立“中国空中公园通联 0-9 区奖状”奖状。

# 第 二 条：申请要求
申请者必须为合法设立的业余电台，且在 [POTA官网](https://parksontheair.com/) 注册账户。
申请者在进行 POTA 活动时的活动地点必须在 POTA 活动官网公布的公园实体范围内，且必须遵守当前所在的公园及无线电管理部门的相关规定。
用于申请奖状的有效通联应当发生于北京时间 2023年10月4日 之后。
通联必须符合国家及地方法律法规之要求，不得使用地面中继台或互联网完成通联。
申请奖状需提交架台照片，照片需体现电台、天线和操作员。
申请奖项除特别规定外，无波段、模式要求。
7.使用多个呼号合并申请时，如果操作者是同一人，可以合并为同一个呼号计算。但是不能使用集体台呼号
# 第 三 条：通联证明
以下类型的通联证明可用于申请该奖状：

POTA官网 日志截图，截图需包含用户名在内的网页全图
纸质 QSL 卡片，申请时需提供正反面之扫描图像。
ARRL Logbook of the World（LoTW）确认证明，申请时需提供 QSO Detail 之截图。
申请者提供的QSL证明（主要为LoTW截图证明或者纸质QSL卡片照片）必须包括如下内容

1 .对方呼号
2 .本方呼号
3 .年月日和时间
4 .波段或频率
5 .工作模式或操作方式
6 .对方的信号报告（RST）
7 .使用卫星通信的，需要有卫星的名称和编号
说明：业余卫星使用的场合，使用接收波段作为通联波段
# 第 四 条：奖状类型及要求
普通奖状：

要求：在任意有 POTA 编号的公园进行通联，成功激活公园（一次通联10个QSO）的同时，与中国大陆0-9区业余电台进行双向 QSO，在日志上传至 POTA 官网后并取得通联证明。
时限要求：申请此奖项的第一个 QSO 与最后一个 QSO 两者相差时间不得超过24小时（1UTC日）
特别奖：

在进行 POTA 通联活动中，通联到的 0-9区 业余电台均在公园发射，则获得特别奖
特别奖时限要求：申请此奖项的第一个 QSO 与最后一个 QSO 两者相差时间不得超过一周
# 第 五 条：申请方式
进入 业余无线电POTA 公众号，点击公园录入按钮，进入奖状申请页面并附通联证明材料。

# 第 六 条：真实性验证
申请人需承诺提供的通联信息真实有效、可供查证。必要时，奖状管理员可要求申请者提供通联证明的原件。若申请者无法按要求提供通联证明，申请作废。
必要时，奖状管理小组可要求申请人提供对方电台为合法设立的业余电台的佐证材料。若无法证明，相关 QSO 不会计入奖项。
申请者提交虚假通联信息或伪造通联证明的，取消其申请和已经签发的奖状，并禁止其再次申请奖状。

# 第 七 条：奖状
奖状大小为 A4，载体为卡纸。载有奖状名称和信息、申请者姓名、呼号、奖状编号、签发日期、奖状管理员署名、防伪贴纸及钢印等。
奖状有电子和纸质两种形式。申请电子奖状的，不收取费用。申请纸质奖状的，中国境内（含港澳台）收取人民币 20 元工本费和邮寄费，申请者自选以邮政挂号或快递到付寄出；中国大陆境外收取人民币 40 元工本费和邮寄费，以水陆路平信寄出。

电子版奖状无防伪贴纸及钢印

奖状由奖状管理小组成员轮流签发。

# 第 八 条：规则解释方
此规则由奖状管理员小组负责解释，如有问题或建议请联系 [bh3xzt@gmail.com](mailto:bh3xzt@gmail.com)。
本规则部分内容参考自[《通联中国学校业余电台奖状申请规则》](https://www.wcsa.ac.cn/)、[《通联全中国所有省、直辖市、自治区、特别行政区奖状(WAPC)申请规则及办法》](https://www.hellocq.net/forum/read.php?tid=350692)
填写问卷代表您已同意并愿意遵守此规则要求

**Comment by Eminlin** [comment]
内容已预先合并，后续需要走流程
https://docs.hamcq.cn/pages/690d3e/
